package cvcenter.entity;
// Generated 15-Dec-2012 09:42:30 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Cv generated by hbm2java This is the entity class for the CV of a student,
 * generated using reverse engineering
 */
public class Cv implements java.io.Serializable {

    //These are the information being hold of a student's CV
    private int cvId;
    private String format;
    private String fileurl;
    private String filename;
    private String jobCat;
    //the owner
    private Student student;
    //the job this CV being applied to
    private Set<Job> jobs = new HashSet<Job>(0);

    //default constructor
    public Cv() {
    }

    //constructor that requires all not-null atrribute
    public Cv(Student student, String fileurl) {
        this.student = student;
        this.fileurl = fileurl;
    }
    //constructor that requires all attributes

    public Cv(Student student, String format, String fileurl, String filename, String jobCat, Set<Job> jobs) {
        this.student = student;
        this.format = format;
        this.fileurl = fileurl;
        this.filename = filename;
        this.jobCat = jobCat;
        this.jobs = jobs;
    }

    //geters and setters
    public int getCvId() {
        return this.cvId;
    }

    public void setCvId(int cvId) {
        this.cvId = cvId;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public String getFormat() {
        return this.format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getFileurl() {
        return this.fileurl;
    }

    public void setFileurl(String fileurl) {
        this.fileurl = fileurl;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getJobCat() {
        return this.jobCat;
    }

    public void setJobCat(String jobCat) {
        this.jobCat = jobCat;
    }

    public Set<Job> getJobs() {
        return jobs;
    }

    public void setJobs(Set<Job> jobs) {
        this.jobs = jobs;
    }
}
