package cvcenter.entity;
// Generated 15-Dec-2012 09:42:30 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java This is the entity class for the student,
 * generated using reverse engineering
 */
public class Student implements java.io.Serializable {

    //The information being hold about a student account
    private Integer studentId;
    private String firstName;
    private String lastName;
    private String email;
    private String tel;
    private String initial;
    //The associated user account
    private Users users;
    //The list of CV being managed by the student
    private Set<Cv> cvs = new HashSet<Cv>(0);

    //default constructor
    public Student() {
    }

    //constructor that requires all not-null attributes
    public Student(Users users, String firstName, String lastName, String email) {
        this.users = users;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    //constructor that requires all attributess
    public Student(Users users, String firstName, String lastName, String email, String tel, String initial, Set<Cv> cvs) {
        this.users = users;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.tel = tel;
        this.initial = initial;
        this.cvs = cvs;
    }

    //getters and setters
    
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getInitial() {
        return this.initial;
    }

    public void setInitial(String initial) {
        this.initial = initial;
    }

    public Set<Cv> getCvs() {
        return this.cvs;
    }

    public void setCvs(Set<Cv> cvs) {
        this.cvs = cvs;
    }
}
