package cvcenter.entity;
// Generated 15-Dec-2012 09:42:30 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java This is the entity class for the users, mainly
 * used for authentication, generated using reverse engineering
 */
public class Users implements java.io.Serializable {

    //information about a user
    private int userId;
    private String username;
    private String password;
    private boolean enabled;
    //The set of student using this user account (should always be just 1), redundance with company
    private Set<Student> students = new HashSet<Student>(0);
    //the set of user role associated with this user account
    private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
    //The set of company using this user account (should always be just 1), redundance with student
    private Set<Company> companies = new HashSet<Company>(0);

    //default constructor
    public Users() {
    }

    //constructor that requires all not-null attributes
    public Users(String username, String password, boolean enabled) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
    }
    //constructor with all attributes

    public Users(String username, String password, boolean enabled, Set<Student> students, Set<UserRoles> userRoleses, Set<Company> companies) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
        this.students = students;
        this.userRoleses = userRoleses;
        this.companies = companies;
    }

    //getters and setters
    
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Set<Student> getStudents() {
        return this.students;
    }

    public void setStudents(Set<Student> students) {
        this.students = students;
    }

    public Set<UserRoles> getUserRoleses() {
        return this.userRoleses;
    }

    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoleses = userRoleses;
    }

    public Set<Company> getCompanies() {
        return this.companies;
    }

    public void setCompanies(Set<Company> companies) {
        this.companies = companies;
    }
}
